language: python

python:
  - 3.7

before_install:
  - sudo apt-get install -y libxml2-dev libxslt-dev

script: python setup.py test

env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2
  - DJANGO=3
  - DJANGO=4

install:
  - export PYTHONPATH=$PWD;
  - export DJANGO_SETTINGS_MODULE=django_test_settings;
  - pip install -q Django==$DJANGO

branches:
  only:
    - master

after_success:
  - coveralls
